title: jinsu's note
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "/jinsubaji" # the subpath of your site, e.g. /blog
url: "https://jinsu1.github.io/jinsubaji" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: κ³µλ¶€λ…ΈνΈ # add your name
author-img: jinsu.jpg # add your photo
about-author:  # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
